### ISSUE TITLE
raja fails to build on gcc@7.3.1 x86_64_v4

### ISSUE THREAD

**Issue by bollig** [LLNL/RAJA#1275]
I have spack CI pipelines building RAJA for targets `x86_64_v4`, `x86_64_v3`, `graviton2` and `aarch64`. Previous versions worked on all four, but raja@2022.03 no longer builds on `x86_64_v4`.  

See e.g., https://gitlab.spack.io/spack/spack/-/jobs/2632742 :

```
/tmp/root/spack-stage/spack-stage-raja-2022.03.0-6wieoyxabftmfzw2fpfkitar2kjz6jsx/spack-src/include/RAJA/policy/tensor/arch/avx512/avx512_int32.hpp:137:19: error: '_mm512_loadu_epi32' was not declared in this scope
         m_value = _mm512_loadu_epi32(ptr);
                   ^~~~~~~~~~~~~~~~~~
/tmp/root/spack-stage/spack-stage-raja-2022.03.0-6wieoyxabftmfzw2fpfkitar2kjz6jsx/spack-src/include/RAJA/policy/tensor/arch/avx512/avx512_int32.hpp:137:19: note: suggested alternative: '_mm512_load_epi32'
         m_value = _mm512_loadu_epi32(ptr);
                   ^~~~~~~~~~~~~~~~~~
                   _mm512_load_epi32
```

**Comment by rhornung67** [comment]
@ajkunen do you see an easy fix for this? Should we make the vectorization stuff a compile time (add RAJA_ENABLE_VECTORIZATION Cmake option) option and turn it off by default?

**Comment by bollig** [comment]
The version of GCC is locked in the pipeline to system-default for Amazon Linux 2 (gcc@7.3.1). We could manually build on another version, but it will take some time. 

The x86_64 chip in use is likely a Skylake / Cascade Lake instance on AWS, but the way Spack gitlab runners are setup on Kubernetes, I don't have direct line of sight into what the hosts look like. The build is not cross-compiled, so the architecture explicitly supports x86_64_v4.

**Comment by rhornung67** [comment]
OK. I found a local Cascade Lake platform and can reproduce the error with GNU 7.3.0 compiler. We'll get someone on it.

**Comment by rchen20** [comment]
@ajkunen This is strange, when I change that line to use `_mm512_load_epi32` (i.e. the aligned load), it works. I also tried passing in `-march=cascadelake` in case there were some headers missing, but apparently gcc/7.3.0 does not support that architecture.

Do you think it's ok to change these intrinsics to use the aligned versions?

**Comment by rhornung67** [comment]
What about the type conversion issue for the register variable? The code should be fine AFAICT.

**Comment by rhornung67** [comment]
@rchen20 can you also check this on tioga or rzvernal?

**Comment by rchen20** [comment]
> What about the type conversion issue for the register variable? The code should be fine AFAICT.

Those functions are supposed to take in an `__mm256i`, but we are passing a member register of type `__mm512i`. I'll try to use other intrinsics to convert this.

> @rchen20 can you also check this on tioga or rzvernal?

On RZVERNAL, it works because the only gcc available there is 10.3.1, and I believe that version of gcc supports architectures like Cascade Lake, while 7.3.x does not.

**Comment by rchen20** [comment]
Even when I pass `-mavx512f` into gcc/7.3.0, it begets the same errors. There must be something special about Cascade Lake where we require a more up-to-date compiler for the AVX-512 instructions.

Rather than apply special fixes for the gcc/7.3.0 + Cascade Lake case, I wonder if we should just warn users to not use `-march=native` and substitute with `-mavx2` for compatibility (AVX-2 definitely works). Let me know what you think @rhornung67 @ajkunen .

**Comment by rhornung67** [comment]
So, it builds with -mavx2?  Alternatively, we could also make the vectorization stuff a compile-time option so folks don't have to build it if they aren't using it.

**Comment by rchen20** [comment]
> So, it builds with -mavx2? Alternatively, we could also make the vectorization stuff a compile-time option so folks don't have to build it if they aren't using it.

It does work with `-mavx2`. I was thinking of something like a `RAJA_ENABLE_VECTORIZATION` CMake option, is that ok?

**Comment by rchen20** [comment]
@bollig This issue should be fixed here https://github.com/LLNL/RAJA/pull/1339. Apparently, older versions of GCC did not implement some of the AVX512 intrinsics. The new PR should work around these issues, and some others.
