### PR TITLE
Cilk fixes

### PR DESCRIPTION
**Pull request by jeffhammond**
The Cilk code appears to have missed out on some header location changes.  This reveals that RAJA Cilk code is not being tested.  I've added a Travis CI test instance to address this.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Ooof, good catches. Looks good to me, pending CI. Thanks for the PR!

**Comment by DavidPoliakoff** [comment]
Some more cogent stuff:

Do we have tests for the Cilk backend? Also, do we want to enable Cilk by adding CMake_CXX_Flags directly, or by doing a RAJA_ENABLE_CILK option? These are worth thinking about for wiser minds, say..... @davidbeckingsale

**Comment by rhornung67** [comment]
We have a RAJA_ENABLE_CILK option (it's off by default), and we have basic unit tests for CILK traversals and reductions.  Note that the reductions are implemented as the original OpenMP reductions were. We haven't bothered to change this since it is not a priority.

The reason we have not been testing cilk in travis is that cilk has been supported natively with the intel compiler only and we have been using the gcc and clang compilers (I'm not sure whether those two support it now).

When we have our testing set up on LC platforms (hopefully soon). We will be doing more comprehensive testing.

**Comment by jeffhammond** [comment]
@rhornung67 Cilk is supported natively in GCC since 5.0 and the failures below with 4.9 might be due to C++11 `auto` and not Cilk (I am too lazy to perform the experiment since no reasonable person uses GCC 4.x anymore :neckbeard:)
```sh
jrhammon@klondike:~/Work/PRK/github-official/Cxx11$ for v in 4.8 4.9 5 6 7 8 ; do echo "Attempting Cilk with GCC $v" ; g++-$v -std=gnu++11 -g -O3 -mtune=native -DPRKVERSION="2.16" -I. transpose-vector-cilk.cc -fcilkplus -o transpose-vector-cilk && echo "SUCCESS" || echo "FAIL" ; done
Attempting Cilk with GCC 4.8
g++-4.8: error: unrecognized command line option ‘-fcilkplus’
FAIL
Attempting Cilk with GCC 4.9
transpose-vector-cilk.cc: In function ‘int main(int, char**)’:
transpose-vector-cilk.cc:116:14: error: expected primary-expression before ‘auto’
   _Cilk_for (auto i=0; i<order; i++) {
              ^
transpose-vector-cilk.cc:116:24: error: ‘i’ was not declared in this scope
   _Cilk_for (auto i=0; i<order; i++) {
                        ^
transpose-vector-cilk.cc:129:18: error: expected primary-expression before ‘auto’
       _Cilk_for (auto it=0; it<order; it+=tile_size) {
                  ^
transpose-vector-cilk.cc:129:29: error: ‘it’ was not declared in this scope
       _Cilk_for (auto it=0; it<order; it+=tile_size) {
                             ^
transpose-vector-cilk.cc:140:18: error: expected primary-expression before ‘auto’
       _Cilk_for (auto i=0;i<order; i++) {
                  ^
FAIL
Attempting Cilk with GCC 5
SUCCESS
Attempting Cilk with GCC 6
SUCCESS
Attempting Cilk with GCC 7
SUCCESS
Attempting Cilk with GCC 8
SUCCESS
```

**Comment by jeffhammond** [comment]
@DavidPoliakoff If I were a person who aspired to create good CMake build systems, I would test for Cilk support and set the appropriate options rather than require the user to specify the GCC flag explicitly (or assume that ICC users are not passing `-no-intel-extensions`, which will disable Cilk), at least when `RAJA_ENABLE_CILK=On`.  A default of `RAJA_ENABLE_CILK=Off` seems prudent, given overwhelmingly likelihood that users will use OpenMP instead.

**Comment by rhornung67** [comment]
@jeffhammond thanks for the info and for contributing. We'll sort this out. But, again, it's a low priority. 

I agree that GCC 4.x can be considered antediluvian. Unfortunately, 4.9.3 is the default on most platforms we need to run on and for one, 4.7.1 is our only option -- I assume you know of the beast of which I speak....

**Comment by jeffhammond** [comment]
@rhornung67 Thank you for teaching me a very useful new work (antediluvian).  Indeed, I am aware of some amazing hardware where vendor GCC support is underwhelming, but I don't expect anyone to use Cilk there, given that Blue Gene has an exceptional OpenMP  runtime.

**Comment by rhornung67** [comment]
No problem. I find it a particularly cromulent word.

**Comment by DavidPoliakoff** [comment]
@jeffhammond , I mentioned this PR offhandedly to a few friends at the lab, most of whom were curious to see how Cilk would do, one is telling me to ping him when this gets merged, as trying it out *should* be as easy as updating a forall_policy and reducer_policy pair of typedefs somewhere. So don't be surprised if you wind up with people asking about Cilk to OpenMP performance comparisons.

**Comment by DavidPoliakoff** [comment]
Also:

```
int main(){
  for(auto i =0 ;i < 100; i++){
  }
}
```

compiles with gcc 4.9.3, which makes me wonder what _Cilk_for is doing, perhaps "i" isn't a loop bound or something else earlier gcc's knew how to handle with auto.

**Comment by trws** [comment]
As I have probably pointed out one too many times for my own good, it is worth noting that "default compiler" doesn't necessarily mean "compiler one should use" or "compiler that should support all new features created for certain template-heavy libraries..."  

Either way, thanks for the PR @jeffhammond, it will be good to have some of this cleaned up!  The only issue seems to be reductions on gcc-6.  Do you see issues with that on your end?

**Comment by jeffhammond** [comment]
@trws My PR fixed the compilation errors associated with RAJA.  I did not test beyond that.  I am using RAJA reducers in my code but I'm only trying to use the OpenMP back-end right now.  I guess I should try `make test`.

**Comment by davidbeckingsale** [comment]
Closing because we are dropping Cilk support in #266
